// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package link

import (
	"context"
	"sync"
)

// Ensure, that ContractMock does implement Contract.
// If this is not the case, regenerate this file with moq.
var _ Contract = &ContractMock{}

// ContractMock is a mock implementation of Contract.
//
//	func TestSomethingThatUsesContract(t *testing.T) {
//
//		// make and configure a mocked Contract
//		mockedContract := &ContractMock{
//			CreateSimpleFunc: func(ctx context.Context, req CreateRequest) (CreateResponse, error) {
//				panic("mock out the CreateSimple method")
//			},
//			RedirectSimpleFunc: func(ctx context.Context, code string) (string, error) {
//				panic("mock out the RedirectSimple method")
//			},
//			ValidateSimpleFunc: func(code []byte) error {
//				panic("mock out the ValidateSimple method")
//			},
//		}
//
//		// use mockedContract in code that requires Contract
//		// and then make assertions.
//
//	}
type ContractMock struct {
	// CreateSimpleFunc mocks the CreateSimple method.
	CreateSimpleFunc func(ctx context.Context, req CreateRequest) (CreateResponse, error)

	// RedirectSimpleFunc mocks the RedirectSimple method.
	RedirectSimpleFunc func(ctx context.Context, code string) (string, error)

	// ValidateSimpleFunc mocks the ValidateSimple method.
	ValidateSimpleFunc func(code []byte) error

	// calls tracks calls to the methods.
	calls struct {
		// CreateSimple holds details about calls to the CreateSimple method.
		CreateSimple []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req CreateRequest
		}
		// RedirectSimple holds details about calls to the RedirectSimple method.
		RedirectSimple []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Code is the code argument value.
			Code string
		}
		// ValidateSimple holds details about calls to the ValidateSimple method.
		ValidateSimple []struct {
			// Code is the code argument value.
			Code []byte
		}
	}
	lockCreateSimple   sync.RWMutex
	lockRedirectSimple sync.RWMutex
	lockValidateSimple sync.RWMutex
}

// CreateSimple calls CreateSimpleFunc.
func (mock *ContractMock) CreateSimple(ctx context.Context, req CreateRequest) (CreateResponse, error) {
	if mock.CreateSimpleFunc == nil {
		panic("ContractMock.CreateSimpleFunc: method is nil but Contract.CreateSimple was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req CreateRequest
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockCreateSimple.Lock()
	mock.calls.CreateSimple = append(mock.calls.CreateSimple, callInfo)
	mock.lockCreateSimple.Unlock()
	return mock.CreateSimpleFunc(ctx, req)
}

// CreateSimpleCalls gets all the calls that were made to CreateSimple.
// Check the length with:
//
//	len(mockedContract.CreateSimpleCalls())
func (mock *ContractMock) CreateSimpleCalls() []struct {
	Ctx context.Context
	Req CreateRequest
} {
	var calls []struct {
		Ctx context.Context
		Req CreateRequest
	}
	mock.lockCreateSimple.RLock()
	calls = mock.calls.CreateSimple
	mock.lockCreateSimple.RUnlock()
	return calls
}

// RedirectSimple calls RedirectSimpleFunc.
func (mock *ContractMock) RedirectSimple(ctx context.Context, code string) (string, error) {
	if mock.RedirectSimpleFunc == nil {
		panic("ContractMock.RedirectSimpleFunc: method is nil but Contract.RedirectSimple was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Code string
	}{
		Ctx:  ctx,
		Code: code,
	}
	mock.lockRedirectSimple.Lock()
	mock.calls.RedirectSimple = append(mock.calls.RedirectSimple, callInfo)
	mock.lockRedirectSimple.Unlock()
	return mock.RedirectSimpleFunc(ctx, code)
}

// RedirectSimpleCalls gets all the calls that were made to RedirectSimple.
// Check the length with:
//
//	len(mockedContract.RedirectSimpleCalls())
func (mock *ContractMock) RedirectSimpleCalls() []struct {
	Ctx  context.Context
	Code string
} {
	var calls []struct {
		Ctx  context.Context
		Code string
	}
	mock.lockRedirectSimple.RLock()
	calls = mock.calls.RedirectSimple
	mock.lockRedirectSimple.RUnlock()
	return calls
}

// ValidateSimple calls ValidateSimpleFunc.
func (mock *ContractMock) ValidateSimple(code []byte) error {
	if mock.ValidateSimpleFunc == nil {
		panic("ContractMock.ValidateSimpleFunc: method is nil but Contract.ValidateSimple was just called")
	}
	callInfo := struct {
		Code []byte
	}{
		Code: code,
	}
	mock.lockValidateSimple.Lock()
	mock.calls.ValidateSimple = append(mock.calls.ValidateSimple, callInfo)
	mock.lockValidateSimple.Unlock()
	return mock.ValidateSimpleFunc(code)
}

// ValidateSimpleCalls gets all the calls that were made to ValidateSimple.
// Check the length with:
//
//	len(mockedContract.ValidateSimpleCalls())
func (mock *ContractMock) ValidateSimpleCalls() []struct {
	Code []byte
} {
	var calls []struct {
		Code []byte
	}
	mock.lockValidateSimple.RLock()
	calls = mock.calls.ValidateSimple
	mock.lockValidateSimple.RUnlock()
	return calls
}
