// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/jr-dragon/dynamic_link/api/base/v1"
	v1_2 "github.com/jr-dragon/dynamic_link/api/link/v1"
	"github.com/jr-dragon/dynamic_link/internal/biz/link"
	"github.com/jr-dragon/dynamic_link/internal/data"
	"github.com/jr-dragon/dynamic_link/internal/server"
)

// Injectors from wire.go:

func wireApp(cfg data.Config) (*App, func(), error) {
	clients, err := data.NewClients(cfg)
	if err != nil {
		return nil, nil, err
	}
	route := v1.NewRoute(clients)
	linkLink := link.NewLink(cfg, clients)
	v1Route := v1_2.NewRoute(linkLink)
	app := server.NewHTTPServer(cfg, route, v1Route)
	mainApp := newApp(app)
	return mainApp, func() {
	}, nil
}
